[package]
name = "rand_wipe"
version = "0.1.0"
authors = ["Adam Lesperance <lespea@gmail.com>"]
edition = "2018"

[dependencies]
crossbeam = "0.7"
fs2 = "0.4"
humantime = "1.3"
indicatif = "0.13"
rand = "0.7"
rand_chacha = "0.2"
rand_hc = "0.2"
rand_isaac = "0.2"
structopt = { version = "0.3", default-features = false }

[profile.release]
codegen-units = 1
lto = true
debug = false