[target.x86_64-pc-windows-msvc]
rustflags = [
    "-Ctarget-feature=+crt-static",
    "-Clink-arg=/DEBUG:NONE",
    "-Cdebuginfo=0"
]

[target.'cfg(not(target_os = "macos"))']
rustflags = [
    "-Ctarget-cpu=native",
]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Clink-arg=-fuse-ld=mold"]
